export const products = [
  {
    id: 1,
    name: "T-shirt with Tape Details",
    rating: 4.5,
    price: 120,
    originalPrice: null,
    discount: null,
    image: "https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png",
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    rating: 3.5,
    price: 240,
    originalPrice: 260,
    discount: 20,
    image: "https://pngimg.com/uploads/jeans/jeans_PNG5775.png",
  },
  {
    id: 3,
    name: "Checkered Shirt",
    rating: 4.5,
    price: 180,
    originalPrice: null,
    discount: null,
    image: "https://pngimg.com/uploads/dress_shirt/dress_shirt_PNG8070.png",
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    rating: 4.5,
    price: 130,
    originalPrice: 160,
    discount: 30,
    image: "https://pngimg.com/uploads/tshirt/tshirt_PNG5448.png",
  },
  {
    id: 5,
    name: "Vertical Striped Shirt",
    rating: 5.0,
    price: 212,
    originalPrice: 235,
    discount: 10,
    image: "https://pngimg.com/uploads/dress_shirt/dress_shirt_PNG8117.png",
  },
  {
    id: 6,
    name: "Courage Graphic T-shirt",
    rating: 4.0,
    price: 145,
    originalPrice: null,
    discount: null,
    image: "https://pngimg.com/uploads/tshirt/tshirt_PNG5438.png",
  },
  {
    id: 7,
    name: "Loose Fit Denim Shorts",
    rating: 3.0,
    price: 80,
    originalPrice: null,
    discount: null,
    image: "https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png",
  },
  {
    id: 8,
    name: "Faded Skinny Jeans",
    rating: 4.5,
    price: 210,
    originalPrice: 250,
    discount: 15,
    image: "https://pngimg.com/uploads/jeans/jeans_PNG5773.png",
  },
];